# Generated by Django 3.0.5 on 2020-04-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agwebberleyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='{% post.title %}', max_length=255),
        ),
    ]
