# Generated by Django 3.0.5 on 2020-04-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agwebberleyapp', '0003_auto_20200420_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
