# Generated by Django 3.0.5 on 2020-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agwebberleyapp', '0004_remove_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='download1',
            field=models.TextField(default='Download1 Link'),
        ),
        migrations.AddField(
            model_name='post',
            name='download1n',
            field=models.TextField(default='Download1 Name}'),
        ),
        migrations.AddField(
            model_name='post',
            name='download2',
            field=models.TextField(default='Download2 Link'),
        ),
        migrations.AddField(
            model_name='post',
            name='download2n',
            field=models.TextField(default='Download2 Name'),
        ),
    ]
