# Generated by Django 3.0.5 on 2020-04-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agwebberleyapp', '0005_auto_20200421_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='download1',
            field=models.CharField(default='Download1 Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='download1n',
            field=models.CharField(default='Download1 Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='download2',
            field=models.CharField(default='Download2 Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='download2n',
            field=models.CharField(default='Download2 Name', max_length=255),
        ),
    ]
