# Generated by Django 3.0.5 on 2020-04-21 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agwebberleyapp', '0006_auto_20200421_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='download1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='download1n',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='download2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='download2n',
            field=models.CharField(max_length=255),
        ),
    ]
