# Generated by Django 3.0.5 on 2020-04-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agwebberleyapp', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
